-- MySQL Script generated by MySQL Workbench
-- чт, 19-сер-2021 10:19:05 +0300
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nextjs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nextjs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nextjs` DEFAULT CHARACTER SET utf8 ;
USE `nextjs` ;

-- -----------------------------------------------------
-- Table `nextjs`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextjs`.`Users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `first_Name` VARCHAR(45) NOT NULL,
  `last_Name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nextjs`.`Properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextjs`.`Properties` (
  `id_Properties` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `rating` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NULL,
  `beds` VARCHAR(45) NOT NULL,
  `baths` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Properties`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nextjs`.`Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextjs`.`Reviews` (
  `id_Reviews` INT NOT NULL AUTO_INCREMENT,
  `feedback` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `id_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Reviews`),
  CONSTRAINT `users`
    FOREIGN KEY (`id_Reviews`)
    REFERENCES `nextjs`.`Users` (`id_users`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
